import { Book } from "~/types/entities/Book";

const books: Book[] = [
	{
		id: "1",
		title: "The Great Gatsby",
		isbn: "9780743273565",
		img: "https://example.com/images/great-gatsby.jpg",
		pages: 180,
		publish_year: 1925,
		stock: 10,
		available_stock: 5,
		shelf: "A1",
		category: ["Fiction", "Classic"],
		author: "F. Scott Fitzgerald",
		publisher: "Charles Scribner's Sons",
	},
	{
		id: "2",
		title: "1984",
		isbn: "9780451524935",
		img: "https://example.com/images/1984.jpg",
		pages: 328,
		publish_year: 1949,
		stock: 8,
		available_stock: 3,
		shelf: "B2",
		category: ["Fiction", "Dystopian"],
		author: "George Orwell",
		publisher: "Secker & Warburg",
	},
	{
		id: "3",
		title: "To Kill a Mockingbird",
		isbn: "9780061120084",
		img: "https://example.com/images/to-kill-a-mockingbird.jpg",
		pages: 281,
		publish_year: 1960,
		stock: 15,
		available_stock: 10,
		shelf: "C3",
		category: ["Fiction", "Classic"],
		author: "Harper Lee",
		publisher: "J.B. Lippincott & Co.",
	},
	{
		id: "4",
		title: "The Catcher in the Rye",
		isbn: "9780316769488",
		img: "https://example.com/images/catcher-in-the-rye.jpg",
		pages: 277,
		publish_year: 1951,
		stock: 5,
		available_stock: 2,
		shelf: "D4",
		category: ["Fiction", "Classic"],
		author: "J.D. Salinger",
		publisher: "Little, Brown and Company",
	},
	{
		id: "5",
		title: "The Hobbit",
		isbn: "9780547928227",
		img: "https://example.com/images/the-hobbit.jpg",
		pages: 310,
		publish_year: 1937,
		stock: 12,
		available_stock: 7,
		shelf: "E5",
		category: ["Fiction", "Fantasy"],
		author: "J.R.R. Tolkien",
		publisher: "George Allen & Unwin",
	},
	{
		id: "6",
		title: "The Great Gatsby",
		isbn: "9780743273565",
		img: "https://example.com/gatsby.jpg",
		pages: 180,
		publish_year: 1925,
		stock: 10,
		available_stock: 5,
		shelf: "Fiction",
		category: ["Classic", "Fiction"],
		author: "F. Scott Fitzgerald",
		publisher: "Scribner",
	},
	{
		id: "7",
		title: "1984",
		isbn: "9780451524935",
		img: "https://example.com/1984.jpg",
		pages: 328,
		publish_year: 1949,
		stock: 15,
		available_stock: 8,
		shelf: "Dystopian",
		category: ["Dystopian", "Fiction"],
		author: "George Orwell",
		publisher: "Harcourt Brace Jovanovich",
	},
	{
		id: "8",
		title: "To Kill a Mockingbird",
		isbn: "9780061120084",
		img: "https://example.com/mockingbird.jpg",
		pages: 281,
		publish_year: 1960,
		stock: 12,
		available_stock: 6,
		shelf: "Fiction",
		category: ["Classic", "Fiction"],
		author: "Harper Lee",
		publisher: "J.B. Lippincott & Co.",
	},
	{
		id: "9",
		title: "The Catcher in the Rye",
		isbn: "9780316769488",
		img: "https://example.com/catcher.jpg",
		pages: 277,
		publish_year: 1951,
		stock: 8,
		available_stock: 3,
		shelf: "Fiction",
		category: ["Classic", "Fiction"],
		author: "J.D. Salinger",
		publisher: "Little, Brown and Company",
	},
	{
		id: "10",
		title: "Pride and Prejudice",
		isbn: "9781503290563",
		img: "https://example.com/pride.jpg",
		pages: 279,
		publish_year: 1813,
		stock: 20,
		available_stock: 15,
		shelf: "Classic",
		category: ["Classic", "Romance"],
		author: "Jane Austen",
		publisher: "CreateSpace Independent Publishing Platform",
	},
	{
		id: "11",
		title: "The Hobbit",
		isbn: "9780547928227",
		img: "https://example.com/hobbit.jpg",
		pages: 310,
		publish_year: 1937,
		stock: 10,
		available_stock: 4,
		shelf: "Fantasy",
		category: ["Fantasy", "Adventure"],
		author: "J.R.R. Tolkien",
		publisher: "George Allen & Unwin",
	},
	{
		id: "12",
		title: "Fahrenheit 451",
		isbn: "9781451673319",
		img: "https://example.com/fahrenheit.jpg",
		pages: 158,
		publish_year: 1953,
		stock: 5,
		available_stock: 2,
		shelf: "Dystopian",
		category: ["Dystopian", "Science Fiction"],
		author: "Ray Bradbury",
		publisher: "Ballantine Books",
	},
	{
		id: "13",
		title: "Brave New World",
		isbn: "9780060850524",
		img: "https://example.com/brave.jpg",
		pages: 268,
		publish_year: 1932,
		stock: 7,
		available_stock: 3,
		shelf: "Dystopian",
		category: ["Dystopian", "Science Fiction"],
		author: "Aldous Huxley",
		publisher: "Chatto & Windus",
	},
	{
		id: "14",
		title: "The Alchemist",
		isbn: "9780062315007",
		img: "https://example.com/alchemist.jpg",
		pages: 208,
		publish_year: 1988,
		stock: 12,
		available_stock: 6,
		shelf: "Fiction",
		category: ["Fiction", "Adventure"],
		author: "Paulo Coelho",
		publisher: "HarperOne",
	},
];


export default books;
